import logging
import sys
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import CORS_ORIGINS
from app.routers import upload, subtitles, status, download

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
    stream=sys.stdout,
)

logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("AutoSub AI Backend starting up")
    yield
    logger.info("AutoSub AI Backend shutting down")


app = FastAPI(
    title="AutoSub AI Backend",
    description=(
        "Upload audio or video files and receive downloadable SRT subtitle files "
        "generated by Faster-Whisper. \n\n"
        "**Workflow:** `POST /upload` → `POST /generate-subtitles` → `GET /status/{job_id}` → `GET /download/{job_id}`"
    ),
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(upload.router)
app.include_router(subtitles.router)
app.include_router(status.router)
app.include_router(download.router)


@app.get("/", tags=["Health"], summary="Root health check")
async def root():
    return {
        "service": "AutoSub AI Backend",
        "version": "1.0.0",
        "status": "ok",
        "docs": "/docs",
    }


@app.get("/health", tags=["Health"], summary="Health check")
async def health():
    return {"status": "ok"}
