import asyncio
import logging
import sys
from concurrent.futures import ThreadPoolExecutor
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import CORS_ORIGINS, WHISPER_MODEL_SIZE
from app.routers import upload, subtitles, status, download, translate
from app.services.transcription_service import warmup_model

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
    stream=sys.stdout,
)

logger = logging.getLogger(__name__)

_warmup_executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix="warmup")


async def _run_warmup() -> None:
    """
    Run model warm-up on a dedicated thread so the event loop stays unblocked.
    Health checks and all routes are available immediately — warm-up runs in parallel.
    Failures are logged but never crash the server.
    """
    loop = asyncio.get_running_loop()
    try:
        await loop.run_in_executor(_warmup_executor, warmup_model)
    except Exception:
        logger.exception("Unexpected error in warm-up task — continuing without pre-loaded model")


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("AutoSub AI Backend starting — model=%s", WHISPER_MODEL_SIZE)

    # Fire warm-up as a background task; yield immediately so /health
    # and all other routes are available before warm-up completes.
    warmup_task = asyncio.create_task(_run_warmup(), name="model-warmup")

    yield

    # Shutdown: cancel warm-up if still running (e.g. very fast restart)
    if not warmup_task.done():
        logger.info("Cancelling in-progress warm-up task")
        warmup_task.cancel()
        try:
            await warmup_task
        except asyncio.CancelledError:
            pass

    _warmup_executor.shutdown(wait=False)
    logger.info("AutoSub AI Backend shut down")


app = FastAPI(
    title="AutoSub AI Backend",
    description=(
        "Upload audio or video files and receive downloadable SRT subtitle files "
        "generated by Faster-Whisper.\n\n"
        "**Workflow:** `POST /upload` → `POST /generate-subtitles` "
        "→ `GET /status/{job_id}` → `GET /download/{job_id}`"
    ),
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(upload.router)
app.include_router(subtitles.router)
app.include_router(status.router)
app.include_router(download.router)
app.include_router(translate.router)


@app.api_route("/", methods=["GET", "HEAD"], tags=["Health"], summary="Root health check")
async def root():
    return {
        "service": "AutoSub AI Backend",
        "version": "1.0.0",
        "status": "ok",
        "docs": "/docs",
    }


@app.get("/health", tags=["Health"], summary="Health check")
async def health():
    return {"status": "ok"}
